//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.28 at 11:29:19 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "com/slabs/collaborate/core/pojo", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.slabs.collaborate.core.pojo;
